// Drives the built site through a farm outing at iPhone size, taking screenshots.
import { chromium, devices } from '@playwright/test';
import { mkdirSync } from 'node:fs';
const out = process.argv[2] ?? 'shots';
const base = process.argv[3] ?? 'http://localhost:4173/FOWL-PLAY/';
const desktop = process.argv[4] === 'desktop';
const device = desktop ? { viewport: { width: 1280, height: 800 } } : { ...devices['iPhone 13'], defaultBrowserType: undefined };
mkdirSync(out, { recursive: true });
const browser = await chromium.launch({ executablePath: '/opt/pw-browsers/chromium' });
const context = await browser.newContext(device);
const page = await context.newPage();
const errors = [];
page.on('console', (m) => { if (m.type() === 'error' && !m.text().includes('ERR_CERT')) errors.push(`${m.type()}: ${m.text()}`); });
page.on('pageerror', (e) => errors.push(`pageerror: ${e.message}`));
let n = 0;
const shot = async (name) => { await page.screenshot({ path: `${out}/${String(++n).padStart(2, '0')}-${name}.png` }); };
await page.goto(base);
await page.waitForSelector('.welcome');
await page.click('.welcome .btn.primary');
await page.click('.welcome .pick >> nth=0');
await page.waitForTimeout(500);
await shot('farm-board');
await page.click('button:has-text("Head out")');
await page.waitForTimeout(400);
await shot('picker');
await page.click('.outing-row .btn.primary >> nth=0');
await page.waitForTimeout(900);
await shot('farm-start');
// walk right with the keyboard until the crate blocks us, jump on it, peck the sack
const cx = () => page.evaluate(() => window.__fowl.farm?.chicken.x ?? 0);
await page.keyboard.down('ArrowRight');
for (let i = 0; i < 40 && (await cx()) < 283; i++) await page.waitForTimeout(100);
await page.keyboard.down(' ');
await page.waitForTimeout(350);
await page.keyboard.up(' ');
await page.waitForTimeout(300);
await page.keyboard.up('ArrowRight');
await page.waitForTimeout(400);
console.log('CHICKEN', JSON.stringify(await page.evaluate(() => { const c = window.__fowl.farm?.chicken; return c ? { x: c.x, y: c.y, anim: c.anim } : null; })));
await shot('on-crate');
for (let i = 0; i < 4; i++) { await page.keyboard.press('e'); await page.waitForTimeout(300); }
await page.waitForTimeout(600);
await shot('breakfast');
const state = await page.evaluate(() => window.__fowl.store.state.farm);
console.log('FARM', JSON.stringify({ missions: state.missions, clues: state.clues }));
if (await page.locator('.farm-card.complete').count()) await page.click('.farm-card button:has-text("Keep exploring")');
await page.keyboard.down('ArrowRight');
await page.waitForTimeout(2600);
await page.keyboard.up('ArrowRight');
await page.waitForTimeout(400);
await shot('hedge');
await page.keyboard.press('Escape');
await page.waitForTimeout(300);
await shot('pause');
await page.click('.farm-card button:has-text("Back to the coop")');
await page.waitForTimeout(500);
await shot('board-after');
await page.click('.nav button:has-text("Fowldex")');
await page.waitForTimeout(300);
await shot('fowldex-flock');
await page.click('.subtabs button:has-text("Abilities")');
await page.waitForTimeout(300);
await shot('fowldex-abilities');
await page.click('.nav button:has-text("Coop")');
await page.waitForTimeout(300);
await shot('coop');
await page.click('.chicken-card >> nth=0');
await page.waitForTimeout(300);
await shot('detail');
console.log('ERRORS', errors.join('\n') || 'none');
await browser.close();
