import { chromium, devices } from '@playwright/test';
import { mkdirSync } from 'node:fs';
const out = process.argv[2] ?? 'shots';
const base = process.argv[3] ?? 'http://localhost:4173/FOWL-PLAY/';
const device = process.argv[4] === 'desktop' ? { viewport: { width: 1280, height: 900 } } : devices['iPhone 13'];
mkdirSync(out, { recursive: true });
const browser = await chromium.launch({ executablePath: '/opt/pw-browsers/chromium' });
const context = await browser.newContext({ ...device, defaultBrowserType: undefined });
const page = await context.newPage();
const errors = [];
page.on('console', (m) => { if (m.type() === 'error' || m.type() === 'warning') errors.push(`${m.type()}: ${m.text()}`); });
page.on('pageerror', (e) => errors.push(`pageerror: ${e.message}`));
let n = 0;
const shot = async (name) => { await page.screenshot({ path: `${out}/${String(++n).padStart(2, '0')}-${name}.png`, fullPage: false }); };
const full = async (name) => { await page.screenshot({ path: `${out}/${String(++n).padStart(2, '0')}-${name}.png`, fullPage: true }); };

await page.goto(base);
await page.waitForSelector('.welcome');
await shot('welcome');
await page.click('.welcome .btn.primary');
await page.waitForTimeout(300);
await shot('pick-second');
await page.click('.welcome .pick >> nth=1'); // Polish
await page.waitForTimeout(600);
await full('breed-preset');
await page.click('button:has-text("Breed")');
await page.waitForTimeout(600);
await full('breed-after-egg');
await page.click('.egg-slot .btn:has-text("Hatch")');
await page.waitForTimeout(400);
await shot('hatch-egg');
await page.click('.egg-big', { force: true });
await page.waitForTimeout(500);
await page.click('.egg-big', { force: true });
await page.waitForTimeout(500);
await shot('hatch-crack');
await page.click('.egg-big', { force: true });
await page.waitForTimeout(1600);
await shot('hatch-reveal');
await page.evaluate(() => document.querySelector('.reveal')?.scrollTo(0, 400));
await shot('hatch-reveal-scrolled');
await page.click('.reveal .btn.primary');
await page.waitForTimeout(800);
await full('coop');
await page.click('.chicken-card >> nth=0');
await page.waitForTimeout(400);
await shot('detail');
await page.evaluate(() => document.querySelector('.modal')?.scrollTo(0, 600));
await shot('detail-scrolled');
await page.click('.modal .close');
await page.click('.nav button:has-text("Almanac")');
await page.waitForTimeout(400);
await full('almanac-breeds');
await page.click('.subtabs button:has-text("Traits")');
await page.waitForTimeout(300);
await full('almanac-traits');
await page.click('.subtabs button:has-text("Milestones")');
await page.waitForTimeout(300);
await full('almanac-milestones');
await page.click('.nav button:has-text("Show")');
await page.waitForTimeout(300);
await full('show');
await page.click('.show-cat >> nth=1');
await page.waitForTimeout(300);
await page.click('.modal .chicken-card >> nth=0');
await page.waitForTimeout(900);
await shot('show-result');
await page.click('.modal .close');
await page.click('.nav button:has-text("Hatchery")');
await page.waitForTimeout(300);
await full('hatchery');
// reload and confirm persistence
await page.reload();
await page.waitForTimeout(600);
await full('after-reload');
const summary = await page.evaluate(() => { const s = window.__fowl.store.state; return { chickens: s.chickens.length, eggs: s.eggs.length, corn: s.corn, traits: Object.keys(s.discoveredTraits).length, breeds: Object.keys(s.discoveredBreeds).length, onboarding: s.onboarding }; });
console.log('STATE', JSON.stringify(summary));
console.log('ERRORS', errors.length ? errors.join('\n') : 'none');
await browser.close();
